### PR TITLE
Normalize boolean params

### PR DESCRIPTION
**Pull request by MartinVondrak**
This PR fixes calculating wrong digest when `DEPOSITFLAG` or other parameters (contained in digest), that have value of boolean, are set to `false`.

According to GP webpay documentation, there is parameter called `DEPOSITFLAG`, that is contained in digest, which is used to verify the request. This parameter has values of boolean type. Problem occures, when `DEPOSITFLAG` parameter is set to `false`, because all parameters are represented as associative array and function implode is called on this array.

In [PHP documentation](http://php.net/manual/fr/function.implode.php#104568) there is confirmed, that implode "called" on array item, that contains `false` does nothing. This leads to following situation in `PaymentRequest`:

- `DEPOSITFLAG` in query string is correctly set to `0`
- `DIGEST` is calculated with empty string as `DEPOSITFLAG`.

The obvious result is that GP webpay denies your request.

I would be really thankful if you merge this pull request and publish new version to packagist, because in my opinion there is no reason to create new fork just because of little bug.

### CODE REVIEW

**Comment by newPOPE** [comment]
Hi, thanks for PR.

Is it require params normalizing in both cases (sign and verify). I think it is required only in sign because params for verifying comes from gateway. Is that right? If yes, can you move params building (correct types) to `PaymentRequest::getParams()`?

**Comment by newPOPE** [comment]
BTW, what version of PHP you are using? If I add typecasts for PHP7 it will fix your problem.

**Comment by MartinVondrak** [comment]
You were right. There is no need to normalize parameters given from GP webpay. So I have moved the code to `PaymentRequest::getParams()`. It might be good idea to change it just to ternary operator in constructor. I think it would be more readable code and also there is no need to iterate over all parameters everytime you call `getParams()` method.

We use PHP7.1 and right now I don't see, where typecasting would be helpful, could you be more specific?

Also build is currently failing, because, there is requirement for PHP>=7.0 and PHP<8.0 in `composer.json`, but travis is configured for versions 5.4, 5.5 and 5.6.

**Comment by newPOPE** [comment]
Hi, here https://github.com/newPOPE/gp-webpay-php-sdk/blob/feature/typecasts/src/AdamStipak/Webpay/PaymentRequest.php I added typecasts and for example `$depositFlag` cannot be boolean only int so (1/0). This is what I meant.

**Comment by MartinVondrak** [comment]
I see, I was a bit narrow-minded and still thinking about typecasting it to string. Your fix is good. Are planning to publish it on packagist as a stable version or should I switch to dev-master?

**Comment by newPOPE** [comment]
I'll publish it.

**Comment by MartinVondrak** [comment]
Thanks! and I guess you can close this PR then.

**Comment by newPOPE** [comment]
Solved via typecasts.

**Pull request closed without merging**
