### PR TITLE
Update of the Addinfo version

### PR DESCRIPTION
**Pull request by rudolfbruder**
Current GP Webpay is using 5.0 version of the Addinfo XML. In order to get ADDINFO parameter working it needs to be updated.

### CODE REVIEW

**Comment by newPOPE** [comment]
Hello,

can you provide and update test for AddInfo https://github.com/newPOPE/gp-webpay-php-sdk/tree/master/tests/AdamStipak/Webpay/PaymentRequest also?

If don't know how, just sent me xsd schema v5 and I will do it.

**Comment by rudolfbruder** [comment]
@newPOPE I will try to make the test by the end of the week on my own. If i wont be able to do it i will let you know 🤓

**Comment by rudolfbruder** [comment]
I have added the v5 xml and replaced it within the test's v4. Please verify if I have done it correctly. Thanks! @newPOPE

**Comment by newPOPE** [comment]
Should be fixed and merged. Can you @rudolfbruder  try&verify master version?

**Comment by rudolfbruder** [comment]
Yeah works for me on DEV environment.

**Comment by newPOPE** [comment]
Version 1.4.0. Thx for help

**Pull request closed without merging**
